name: QA Automation CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run API tests with Newman
        run: |
          npx newman run api-tests/crud-api-tests.json \
          -r cli,html,htmlextra \
          --reporter-html-export api-tests/report.html
